services:
  - type: web
    name: be-todo-auto
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d10i9rmmcj7s73boqa1g-a.oregon-postgres.render.com
      - key: DB_USER
        value: todo_db_user
      - key: DB_PASSWORD
        value: QGjLos69J7kDcKHWxZrvU2E0eghYoVCf
      - key: DB_NAME
        value: todo_db_25hq
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo-auto
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-auto.onrender.com